### ISSUE TITLE
Telegram bot non risponde

### ISSUE THREAD

**Issue by jacopomarcovaldi** [jpnos26/thermostat_v4#2]
Salve,
ho notato che dopo un po' di tempo (circa 1 ora) il bot di telgram smette di risponde. Il messaggio ha la doppia spunta quindi viene ricevuto ma il bot non risponde.
Una volta chiuso e riaperto il processo termostat.py tutto torna a funzionare correttamente.
L'interfaccia sullo schermo touch e quella web funzionano correttamente per cui sembra che sia proprio la parte di codice del bot che ha dei problemi.
Qualcuno sa aiutarmi?
Grazie.

**Comment by jpnos26** [comment]
Ciao
A me non succede prova a cancellare la cronologia del bot e quindi riavvia
Il mio è in funzione da giorni
Comunque provo ad indagare
Poi come ti ho detto iscriviti su raspberry Italy che probabilmente hai più risposte
Jpnos

⁣Inviato da BlueMail ​

Il giorno 1 dic 2017, 14:30, alle ore 14:30, Jacopo <notifications@github.com> ha scritto:

**Comment by jacopomarcovaldi** [comment]
Grazie per la risposta.
Non avevo letto/visto la risposta in cui mi dicevi di controllare Raspberry italy.
Come avrai visto ho modificato il codice per avere un minimo di sicurezza quando si usa il bot. In questo modo solo chi è autorizzato può interagire con il cronotermostato.

**Comment by jpnos26** [comment]
No non vedo la modifica, non saprei dove l'hai messa
Fammi vedere il codice, comunque la protezione puoi averla lato telegram

**Comment by jacopomarcovaldi** [comment]
Eh non sono molto esperto di git per cui ho paura di aver sbagliato a segnalarti la modifica.
Ah non sapevo si potesse fare lato telegram.
In ogni caso il codice della parte telegram è diventato questo:
if telegramSend == 1:
    bot = telepot.Bot(settings.get("telegram")["token"])
    with thermostatLock:
        def handle(msg):
            id_a = [1234567890,2222222,3333333,4444444,5555555]
            chat_id = msg['chat']['id']
            command = msg['text']
            sender = msg['from']['id']
            #print 'Got command: %s' % command
            if sender in id_a:
                if command == "/ip":
                    f = get("https://api.ipify.org").text
                    look_ip = str(f)
                    if cherrypy.server.socket_port == 443:
                        bot.sendMessage(chat_id, "Da Internet Thermostat su: https://" + look_ip + "/")
                    else:
                        bot.sendMessage(chat_id, "Da Internet Thermostat su: http://" + look_ip + "/")
                    ip_int = str(get_ip_address())
                    if cherrypy.server.socket_port == 443:
                        bot.sendMessage(chat_id, "Da Lan Thermostat su: https://" + ip_int + "/")
                    else:
                        bot.sendMessage(chat_id, "Da Lan Thermostat su: http://" + ip_int + "/")
                elif command == "/stato":
                    bot.sendMessage(chat_id, test_ip)
                elif command == "/time":
                    bot.sendMessage(chat_id, str(datetime.datetime.now().strftime("%H:%M -- %d/%m/%Y")))
                elif command[:8] == "/setTemp":
                    tempe_set = command[command.index(":")+1:]
                    #print str(tempe_set),str(setTemp)
                    settaTemp(float(tempe_set))
                    change_system_settings()
                    bot.sendMessage(chat_id, "Set Temp : "+str(setTemp))
                    bot.sendMessage(chat_id, test_ip)
                elif command == "/help":
                    risposta = "/ip : leggi ip Thermostat \n/time : leggi ora Thermostat \n/stato : leggi lo stato di Thermostat \n/settemp:20.0 : setta Temperatura \n/inverno : setta Sistema per inverno \n/estate : setta Sistema per Es$
                    bot.sendMessage(chat_id,risposta)
                elif command == "/Inverno":
                    setControlState(heatControl, "down")
                    holdControl.state="normal"
                    change_system_settings()
                    bot.sendMessage(chat_id,"Settato Inverno")
                    bot.sendMessage(chat_id, test_ip)
                elif command == "/Estate":
                    setControlState(coolControl, "down")
                    holdControl.state="normal"
                    change_system_settings()
                    bot.sendMessage(chat_id,"Settato Estate")
                    bot.sendMessage(chat_id, test_ip)
                elif command == "/Manuale":
                    setControlState(holdControl, "down")
                    change_system_settings()
                    bot.sendMessage(chat_id,"Settato Manuale")
                    bot.sendMessage(chat_id, test_ip)
                elif command =="/Off":
                   holdControl.state="normal"
                   coolControl.state="normal"
                   setControlState(heatControl, "normal")
                   change_system_settings()
                   bot.sendMessage(chat_id, test_ip)
            else:
                bot.sendMessage(chat_id,"Non sei autorizzato ad utilizzare questo bot")

Una miglioria può essere aggiungere la lista degli id all'interno del json.

**Comment by jpnos26** [comment]
Ok 
puoi settare /setprivacy in botFather
come si chiama il tuo bot ....... ?
cosi provo a vedere se posso raggiungerlo..... di regola solo tu puoi farlo a meno non lo metti in un gruppo

**Comment by jacopomarcovaldi** [comment]
Ho già fatto provare ad un mio amico e lo raggiunge. 
Il comando che mi hai segnalato tu serve a questo:

'Enable' - your bot will only receive messages that either start with the '/' symbol or mention the bot by username.
'Disable' - your bot will receive all messages that people send to groups.
Current status is: ENABLED

Ho aggiunto il codice proprio perchè cercando tra le varie opzioni del botfather non ho trovato un modo per bloccare l'accesso al bot.

**Comment by jpnos26** [comment]
mmmmmm
strano ....... bisogna indaghi .....
e ti so dire . Guardo nelle api 
Puoi aggiungerlo ad un gruppo chiuso con amministratore e dal quale solo tu puoi dare accesso

**Comment by jacopomarcovaldi** [comment]
Ok, mi può tornare il discorso del gruppo chiuso, ma in generale è sempre ricercabile e quindi chiunque può trovarlo, fare /start e mandare qualche comando.
Capisco che il rischio sicurezza sia minimo eh, non è che non ci dormo la notte, però se si può evitare sono più contento. :)

**Comment by jpnos26** [comment]
Aggiunta la parte secured per telegram
Ora il sistema risponde solo ad una chat_id che si e abilitata con una pwd

**Comment by jacopomarcovaldi** [comment]
Ti ringrazio per l'aggiunta.
Io purtroppo, continuo ad avere blocchi del bot di telegram, ma non riesco a capire come mai.
Sia che lo interpelli, sia che non lo faccia dopo un tot di tempo, che varia da 30 minuti ad 1 ora, il bot smette di rispondere.

**Comment by jpnos26** [comment]
Hai altri software che girano su rasp ?
Se provi a cancellare la cronologia su telegram e riavviare , riparte ?

**Comment by jacopomarcovaldi** [comment]
Anche io ho pensato la solita cosa, così ho fatto una installazione pulita di raspbian stretch lite e ho installato di nuovo il progetto. Il problema si è riproposto. Dato che questa prova ha eliminato il sospetto che plex media server desse fastidio, ho reinstallato di nuovo anche lui. La cronologia intendi nella chat sul client? Se intendi quella si, ho provato a cancellarla e riavviare il tutto ma niente.

**Comment by jpnos26** [comment]
Nel codice del l'ultimo thermostat
def handle(msg):
            global telegramTimeout, chatIdTest,testTimeout
            chat_id = msg['chat']['id']
            command = msg['text']
            print 'Got command: %s' % command
            print chat_id
i due print sono il comando che ricevi e te lo visualizza nella consolle.
cosi vedi in consolle se arrivano i comandi oppure no

**Comment by jacopomarcovaldi** [comment]
Grazie ci provo.

**Comment by jacopomarcovaldi** [comment]
Ciao, dopo la modifica che mi hai consigliato, il bot gira da un giorno senza problemi.
Ovviamente una print non sarà sicuramente la soluzione al problema, però il risultato ottenuto è quello che volevo quindi buono così. :+1:

**Comment by jpnos26** [comment]
Ciao 
Tra poco metto su git
un'ulteriore modifica con la gestione degli errori di telegram 
E la pagina web per cellulare
Vedrai questa funziona ancora meglio
Ciao

⁣Inviato da BlueMail ​

Il giorno 6 dic 2017, 10:15, alle ore 10:15, Jacopo <notifications@github.com> ha scritto:

**Comment by jacopomarcovaldi** [comment]
Ottimo grazie.
