### ISSUE TITLE
Modalità manuale temporizzata

### ISSUE THREAD

**Issue by grossialex** [jpnos26/thermostat_v4#3]
sarebbe utile un comando per implementare la cosiddetta modalità "manuale temporizzata" che permetta di settare la modalità manuale impostando <temp> gradi per <temp> minuti per poi tornare alla modalità schedulata (inverno/estate)
/manualeTemporizzata:<temp>|<time> (es. /manualeTemporizzata:20|120)

**Comment by grossialex** [comment]
- [ ]

**Comment by jpnos26** [comment]
Ci si puo ragionare ..........
